name: Build APK
run-name: Pembuatan APK Otomatis
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  bangun-apk:
    name: Proses Pembuatan APK
    runs-on: ubuntu-latest
    steps:
      - name: Ambil semua kode dari repositori
        uses: actions/checkout@v4

      - name: Siapkan Java 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      # ✅ File dibuat TEPAT di folder utama (sesuai kode build.gradle.kts kamu)
      - name: Buat file kunci tanda tangan debug
        run: |
          keytool -genkey -noprompt \
            -alias androiddebugkey \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -keystore debug.keystore \
            -storepass android -keypass android \
            -dname "CN=Android Debug,O=Android,C=US"

      - name: Mulai proses pembuatan APK
        run: gradle assembleDebug --no-daemon --stacktrace

      - name: Simpan file APK jadi arsip
        uses: actions/upload-artifact@v4
        with:
          name: Hasil-APK-Aplikasi
          path: app/build/outputs/apk/debug/*.apk
          retention-days: 7
