name: Build APK
on:
  push:
    branches: [ main ] # Sesuaikan kalau cabang utamamu bukan "main"
  workflow_dispatch: # Bisa jalan manual lewat tombol

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil Kode
        uses: actions/checkout@v4

      - name: Siapkan Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Beri Izin Gradle
        run: chmod +x gradlew

      - name: Bangun APK
        run: ./gradlew assembleDebug # Ganti jadi assembleRelease kalau mau versi rilis

      - name: Unggah Hasil APK
        uses: actions/upload-artifact@v4
        with:
          name: File-APK
          path: app/build/outputs/apk/debug/*.apk
          
